#!/bin/sh
set -e

#  Reload monit if it is running
monit reload 2>/dev/null || true

# Manually added.  Should be done by automatically dh_python2:
if which pycompile >/dev/null 2>&1; then
    pycompile -p vxfld
fi
